### PR TITLE
Fix exception when parsing a file which worked in 0.12

### PR DESCRIPTION
**Pull request by TikiTDO**
Started getting an exception after updating to `0.13`: 

```
   NoMethodError:
       undefined method `stream' for #<HexaPDF::Reference [22, 0]>
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:308:in `block in contents'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `each'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `each_with_object'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:305:in `contents'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page.rb:455:in `to_form_xobject'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page_tree_node.rb:226:in `block in each_page'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `block in each'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `each_index'
     # .../hexapdf-0.13.0/lib/hexapdf/pdf_array.rb:180:in `each'
     # .../hexapdf-0.13.0/lib/hexapdf/type/page_tree_node.rb:224:in `each_page'
     # .../hexapdf-0.13.0/lib/hexapdf/document/pages.rb:131:in `each'
```

This was able to fix my problem.

### CODE REVIEW

**Comment by gettalong** [comment]
Thanks for bringing this bug to my attention!

Your proposed fix would work in this special case but doesn't fix the underlying problem; which is `HexaPDF::PDFArray#to_ary` not returning an array with preprocessed values. I have implemented the proper fix which will be in the next release.

**Comment by TikiTDO** [comment]
Awesome, thanks. I'm happy to see any working solution. I find PRs like this tend to be the best at illustrating the problem, though getting a proper architectural solution is even better.

**Comment by KjellMorgenstern** [comment]
I ran into an issue which might be related to this. 
With 0.13 I got `undefined method 'stream'`, both, when calling
`HexaPDF::ImageLoader::PDF.load()` 
and when calling 
```
doc = HexaPDF::Document.open(other)
doc.pages[0].to_form_xobject
```
I tried the gem with latest master, but the issue persists, although a different line in the code then in the original report:

`.../.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/hexapdf-8f37c60bc459/lib/hexapdf/type/page.rb:307:in `block in contents': undefined method `stream' for #<HexaPDF::Reference [71, 0]> (NoMethodError)
`

**Comment by TikiTDO** [comment]
@KjellMorgenstern Looking at the commit activity, it doesn't look like the fix @gettalong mentioned is in `master` or `devel` yet. If you need this fix ASAP, then based on the discussion you may be able to use my workaround above, or you could try applying the recommended solution, which you should be able to accomplish by forking and changing [this line](https://github.com/gettalong/hexapdf/blob/8f37c60bc4595afacbb921de81b2b7a1b2cc2c74/lib/hexapdf/pdf_array.rb#L186) in a local fork to something like so (Not tested, just inferring based on what was said):

```ruby
def to_ary
  value.dup.map! {|item| process_entry(item) }
end
```

**Comment by KjellMorgenstern** [comment]
I have tried the to_ary patch and it works. Now the approach to include a pdf with `my_canvas.image('other.pdf', at: ...)`  also works.

**Comment by gettalong** [comment]
@TikiTDO @KjellMorgenstern The next release with the fix will be before 2021 :)
